spring.application.name=imobiliaria

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Imobiliaria?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# THYMELEAF
spring.thymeleaf.cache=false

# Multipart / Upload de Fotos (max 10 imagens, 5MB cada)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=55MB

# E-mail
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=
# spring.mail.password=
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
